# Generated by Django 2.0.9 on 2018-10-03 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryid',
            old_name='depth1',
            new_name='cat_depth1',
        ),
        migrations.RenameField(
            model_name='categoryid',
            old_name='depth2',
            new_name='cat_depth2',
        ),
        migrations.RenameField(
            model_name='categoryid',
            old_name='depth3',
            new_name='cat_depth3',
        ),
    ]
