# Generated by Django 2.0.9 on 2018-10-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20181004_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='active',
        ),
        migrations.RemoveField(
            model_name='item',
            name='enroll',
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('active', '활성화'), ('enrolled', '등록중'), ('deleted', '삭제')], default='active', max_length=30),
        ),
    ]
