# Generated by Django 2.0.9 on 2018-10-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_item_local_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='want_day_end',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='like',
            name='want_day_start',
            field=models.DateField(auto_now=True),
        ),
    ]
