# Generated by Django 2.0.9 on 2018-11-10 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20181102_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='index_image',
        ),
    ]
